#!/usr/bin/env julia
"""
DiffDose neutropenia timing analysis.

This experiment driver imports the translated model from
`utils/NeutropeniaDDEModel.jl`, optimizes one 300 microgram filgrastim administration
time in each of seven CHOP-14 cycles, and writes convergence, schedule, ANC,
and configuration outputs.

The timing controls use sharp sigmoid onset maps (`SIGMOID_EPS = 0.0005` day)
inside the DDE right-hand side. ForwardDiff therefore differentiates the
smoothed, discretized timing objective. This is distinct from the fixed-time
callback path exposed by the model module and from exact fixed-time amplitude
jumps in `IDR.py` and `utils/MosunModel.jl`.

Quick smoke test:

    julia +1.11.6 --project=environments/dde NeutropeniaDDE.jl --preset quick --output output

Manuscript configuration:

    julia +1.11.6 --project=environments/dde NeutropeniaDDE.jl --preset paper --methods all --output output

Scientific sources and DOI links are listed in
`utils/NeutropeniaDDEModel.jl`.
"""


include(joinpath(@__DIR__, "utils", "NeutropeniaDDEModel.jl"))
using .NeutropeniaDDEModel.Parameters
using .NeutropeniaDDEModel.Dosing
using .NeutropeniaDDEModel.SolverUndeclared

"""
7-Cycle CHOP-14 Benchmark  — G-CSF timing optimisation in 7 dimensions.

Decision variable: x ∈ ℝ⁷ — injection day within each cycle (relative to cycle start).
    Absolute injection time for cycle c (0-indexed) = c*14 + x[c+1].

Methods (same 6):
  1. AD + ADAM          (ForwardDiff gradient)
  2. AD + L-BFGS        (ForwardDiff gradient, box-constrained)
  3. FD + ADAM          (central-difference gradient, h = 1e-4)
  4. FD + L-BFGS        (Optim finite-diff L-BFGS, box-constrained)
  5. Nelder–Mead        (derivative-free simplex)
  6. Simulated Annealing (derivative-free stochastic)

All start from x₀ = [4, 4, 4, 4, 4, 4, 4]  (G-CSF on day 4 of each cycle).
Computational budget: 600 forward DDE solves.
  • AD+ADAM:  1 AD solve + 1 loss = 2 per iter  → 300 iters
  • FD+ADAM:  2×7 central diff + 1 loss = 15 per iter → 40 iters
  → ∼8× more gradient steps for AD, which is the central demonstration.

Outputs:
  • CSV  – per-method convergence history + summary table + ANC traces
  • JSON – full configuration
  • Figures generated by companion script `Figures/plot_Figure3.jl`
"""

using Printf, Statistics, Random, DifferentialEquations, Dates
import ForwardDiff
using Optim
using JSON3, CSV, DataFrames

# ── Constants ──────────────────────────────────────────────
const ANC_SCALE   = 8.19
const ANC_IDX     = 2
const CYCLE_LEN   = 14.0
const N_CYCLES    = 7
const T_END       = N_CYCLES * CYCLE_LEN   # 98 days
const CHEMO_W     = 1.0 / 24.0
const DOSE_AMT    = 300_000.0
const SIGMOID_EPS = 0.0005
const ANC_THR     = 2.0
const SAVEAT      = 0.05
const T_MIN       = 0.5          # earliest injection relative to cycle start
const T_MAX       = 13.0         # latest
const T_INIT      = 4.0          # initial condition per cycle
const FD_STEP     = 1e-4
const DIM         = N_CYCLES     # 7-dimensional problem


function parse_cli(args)
    options = Dict{String,String}(
        "preset" => "quick",
        "methods" => "diffdose",
        "output" => joinpath(@__DIR__, "output"),
    )
    index = 1
    while index <= length(args)
        flag = args[index]
        flag in ("--preset", "--methods", "--output") ||
            throw(ArgumentError("Unknown option: $flag"))
        index == length(args) && throw(ArgumentError("Missing value after $flag"))
        options[flag[3:end]] = args[index + 1]
        index += 2
    end
    options["preset"] in ("quick", "paper") ||
        throw(ArgumentError("--preset must be quick or paper"))
    options["methods"] in ("diffdose", "all") ||
        throw(ArgumentError("--methods must be diffdose or all"))
    return options
end

# ── Loss function (7-cycle) ───────────────────────────────
"""
    timing_loss_7c(x)

x is a 7-element vector: x[c] = G-CSF injection day relative to cycle c-1 start.
Loss = ∫₀⁹⁸ max(0, 2.0 − ANC(t)) dt  (trapezoidal).
"""
function timing_loss_7c(x::AbstractVector{D}) where D
    p = default_parameters(D)
    p.AdminChemo = 1; p.AdminGCSF = 1; p.DayAdminChemo = D(0.0)
    p.DeltaC = D(CHEMO_W); p.Period = D(CYCLE_LEN)
    p.NumAdminsChemo = N_CYCLES; p.DoseChemo = D(4000.0)
    p.TotalDose = D(4000.0) * p.BSA; p.Dose = D(DOSE_AMT)
    p.GCSFPeriod = D(1.0); p.AdminsGCSF = 1; p.AdminDay = D(8.0)
    recompute_derived!(p)

    tspan = (0.0, T_END)   # Float64 — tspan doesn't depend on x

    # Build chemo schedule: one infusion at the start of each cycle (Float64 times)
    cs = [ChemoInfusion(Float64(c * CYCLE_LEN), p.TotalDose, p.DeltaC) for c in 0:N_CYCLES-1]

    # Build G-CSF schedule: one injection per cycle at the optimised time (Dual via x)
    gs = [GCSFInjection(D(c * CYCLE_LEN) + x[c+1], D(DOSE_AMT)) for c in 0:N_CYCLES-1]

    sol = solve_scenario_undeclared(p, tspan;
        chemo_schedule=cs, gcsf_schedule=gs,
        smooth_chemo=true,  chemo_smooth_shape=:sigmoid, chemo_smooth_width=D(SIGMOID_EPS),
        smooth_gcsf=true,   gcsf_smooth_shape=:sigmoid,  gcsf_smooth_width=D(SIGMOID_EPS),
        reltol=1e-8, abstol=1e-8, dtmax=1e-2, saveat=SAVEAT)

    loss = zero(D); thr = D(ANC_THR)
    for i in 2:length(sol.t)
        dt = sol.t[i] - sol.t[i-1]
        a1 = D(ANC_SCALE) * sol.u[i-1][ANC_IDX]
        a2 = D(ANC_SCALE) * sol.u[i][ANC_IDX]
        loss += D(0.5) * (max(zero(D), thr - a1) + max(zero(D), thr - a2)) * dt
    end
    return loss
end

# Float64-only wrapper
timing_loss_7c_f64(x::Vector{Float64}) = timing_loss_7c(x)

# ── AD gradient (ForwardDiff, 7-dim) ──────────────────────
function ad_gradient_7c(x::Vector{Float64})
    return ForwardDiff.gradient(timing_loss_7c, x)
end

# ── FD gradient (central difference, 2×7 + 1 loss = 15 solves) ─
function fd_gradient_7c(x::Vector{Float64})
    g = zeros(DIM)
    for d in 1:DIM
        xp = copy(x); xp[d] += FD_STEP
        xm = copy(x); xm[d] -= FD_STEP
        g[d] = (timing_loss_7c_f64(xp) - timing_loss_7c_f64(xm)) / (2 * FD_STEP)
    end
    return g
end

# ── ADAM (vector) ─────────────────────────────────────────
function adam_step_vec!(θ, g, m, v, iter; lr=0.05, β1=0.9, β2=0.999, ε=1e-8)
    for d in 1:length(θ)
        m[d] = β1 * m[d] + (1 - β1) * g[d]
        v[d] = β2 * v[d] + (1 - β2) * g[d]^2
        m̂ = m[d] / (1 - β1^iter)
        v̂ = v[d] / (1 - β2^iter)
        θ[d] -= lr * m̂ / (sqrt(v̂) + ε)
        θ[d] = clamp(θ[d], T_MIN, T_MAX)
    end
end

# ── History record ─────────────────────────────────────────
struct MethodResult7C
    name::String
    best_x::Vector{Float64}      # 7-element optimised timing
    best_loss::Float64
    loss_history::Vector{Float64}
    time_history::Vector{Float64}
    solve_history::Vector{Int}
    total_solves::Int
    wall_time::Float64
end

struct BudgetExhausted <: Exception end

# =====================================================================
#  METHOD 1:  AD + ADAM  (2 solves / iter)
# =====================================================================
function run_ad_adam_7c(; budget, lr=0.05)
    θ = fill(T_INIT, DIM)
    m = zeros(DIM); v = zeros(DIM)
    best_loss = Inf; best_x = copy(θ)
    losses = Float64[]; times = Float64[]; solves = Int[]
    n_solve = 0; t0 = time()

    n_iters = budget ÷ 2
    for iter in 1:n_iters
        g = ad_gradient_7c(θ)               # 1 AD forward solve
        l = timing_loss_7c_f64(θ)           # 1 forward solve
        n_solve += 2
        if l < best_loss; best_loss = l; best_x = copy(θ); end
        push!(losses, best_loss); push!(times, time()-t0); push!(solves, n_solve)
        adam_step_vec!(θ, g, m, v, iter; lr=lr)
    end
    return MethodResult7C("AD+ADAM", best_x, best_loss, losses, times, solves,
                          n_solve, time()-t0)
end

# =====================================================================
#  METHOD 2:  AD + L-BFGS  (box-constrained, hard budget cap)
# =====================================================================
function run_ad_lbfgs_7c(; budget)
    n_solve = Ref(0)
    losses = Float64[]; tms = Float64[]; svs = Int[]
    best_loss = Ref(Inf); best_x = Ref(fill(T_INIT, DIM))
    t0 = time()

    function fg!(F, G, x)
        n_solve[] >= budget && throw(BudgetExhausted())
        xc = clamp.(x, T_MIN, T_MAX)
        l = timing_loss_7c_f64(xc); n_solve[] += 1
        if l < best_loss[]; best_loss[] = l; best_x[] = copy(xc); end
        push!(losses, best_loss[]); push!(tms, time()-t0); push!(svs, n_solve[])
        if G !== nothing
            n_solve[] >= budget && throw(BudgetExhausted())
            G .= ad_gradient_7c(xc); n_solve[] += 1
        end
        if F !== nothing; return l; end
    end

    try
        Optim.optimize(Optim.only_fg!(fg!),
                       fill(T_MIN, DIM), fill(T_MAX, DIM), fill(T_INIT, DIM),
                       Fminbox(LBFGS()),
                       Optim.Options(iterations=10_000, f_abstol=1e-14,
                                     g_tol=1e-12, allow_f_increases=true))
    catch e
        e isa BudgetExhausted || rethrow(e)
    end
    return MethodResult7C("AD+LBFGS", best_x[], best_loss[], losses, tms, svs,
                          n_solve[], time()-t0)
end

# =====================================================================
#  METHOD 3:  FD + ADAM  (2D+1 = 15 solves / iter)
# =====================================================================
function run_fd_adam_7c(; budget, lr=0.05)
    θ = fill(T_INIT, DIM)
    m = zeros(DIM); v = zeros(DIM)
    best_loss = Inf; best_x = copy(θ)
    losses = Float64[]; times = Float64[]; solves = Int[]
    n_solve = 0; t0 = time()

    solves_per_iter = 2 * DIM + 1   # 15
    n_iters = budget ÷ solves_per_iter
    for iter in 1:n_iters
        g = fd_gradient_7c(θ)               # 2*7 = 14 solves
        l = timing_loss_7c_f64(θ)           # 1 solve
        n_solve += solves_per_iter
        if l < best_loss; best_loss = l; best_x = copy(θ); end
        push!(losses, best_loss); push!(times, time()-t0); push!(solves, n_solve)
        adam_step_vec!(θ, g, m, v, iter; lr=lr)
    end
    return MethodResult7C("FD+ADAM", best_x, best_loss, losses, times, solves,
                          n_solve, time()-t0)
end

# =====================================================================
#  METHOD 4:  FD + L-BFGS  (box-constrained, hard budget cap)
# =====================================================================
function run_fd_lbfgs_7c(; budget)
    n_solve = Ref(0)
    losses = Float64[]; tms = Float64[]; svs = Int[]
    best_loss = Ref(Inf); best_x = Ref(fill(T_INIT, DIM))
    t0 = time()

    function f(x)
        n_solve[] >= budget && throw(BudgetExhausted())
        xc = clamp.(x, T_MIN, T_MAX)
        l = timing_loss_7c_f64(xc); n_solve[] += 1
        if l < best_loss[]; best_loss[] = l; best_x[] = copy(xc); end
        push!(losses, best_loss[]); push!(tms, time()-t0); push!(svs, n_solve[])
        return l
    end

    try
        Optim.optimize(f, fill(T_MIN, DIM), fill(T_MAX, DIM), fill(T_INIT, DIM),
                       Fminbox(LBFGS()),
                       Optim.Options(iterations=10_000, f_abstol=1e-14,
                                     g_tol=1e-12, allow_f_increases=true))
    catch e
        e isa BudgetExhausted || rethrow(e)
    end
    return MethodResult7C("FD+LBFGS", best_x[], best_loss[], losses, tms, svs,
                          n_solve[], time()-t0)
end

# =====================================================================
#  METHOD 5:  Nelder–Mead  (hard budget cap)
# =====================================================================
function run_nelder_mead_7c(; budget)
    n_solve = Ref(0)
    losses = Float64[]; tms = Float64[]; svs = Int[]
    best_loss = Ref(Inf); best_x = Ref(fill(T_INIT, DIM))
    t0 = time()

    function f(x)
        n_solve[] >= budget && throw(BudgetExhausted())
        xc = clamp.(x, T_MIN, T_MAX)
        l = timing_loss_7c_f64(xc); n_solve[] += 1
        if l < best_loss[]; best_loss[] = l; best_x[] = copy(xc); end
        push!(losses, best_loss[]); push!(tms, time()-t0); push!(svs, n_solve[])
        return l
    end

    try
        Optim.optimize(f, fill(T_INIT, DIM), NelderMead(),
                       Optim.Options(iterations=10_000, f_abstol=1e-14))
    catch e
        e isa BudgetExhausted || rethrow(e)
    end
    return MethodResult7C("Nelder-Mead", best_x[], best_loss[], losses, tms, svs,
                          n_solve[], time()-t0)
end

# =====================================================================
#  METHOD 6:  Simulated Annealing  (hard budget cap)
# =====================================================================
function run_sim_anneal_7c(; budget)
    n_solve = Ref(0)
    losses = Float64[]; tms = Float64[]; svs = Int[]
    best_loss = Ref(Inf); best_x = Ref(fill(T_INIT, DIM))
    t0 = time()

    function f(x)
        n_solve[] >= budget && throw(BudgetExhausted())
        xc = clamp.(x, T_MIN, T_MAX)
        l = timing_loss_7c_f64(xc); n_solve[] += 1
        if l < best_loss[]; best_loss[] = l; best_x[] = copy(xc); end
        push!(losses, best_loss[]); push!(tms, time()-t0); push!(svs, n_solve[])
        return l
    end

    try
        Optim.optimize(f, fill(T_MIN, DIM), fill(T_MAX, DIM), fill(T_INIT, DIM),
                       SAMIN(; rt=0.9),
                       Optim.Options(iterations=10_000))
    catch e
        e isa BudgetExhausted || rethrow(e)
    end
    return MethodResult7C("Simulated Annealing", best_x[], best_loss[], losses, tms, svs,
                          n_solve[], time()-t0)
end

# ── Solve ANC trajectory (7-cycle) ────────────────────────
function solve_anc_7c(x_inj::Vector{Float64}; gcsf_flag=1)
    p = default_parameters(Float64)
    p.AdminChemo=1; p.AdminGCSF=gcsf_flag; p.DayAdminChemo=0.0; p.DeltaC=CHEMO_W
    p.Period=CYCLE_LEN; p.NumAdminsChemo=N_CYCLES; p.DoseChemo=4000.0
    p.TotalDose=4000.0*p.BSA; p.Dose=DOSE_AMT
    recompute_derived!(p)
    tspan = (0.0, T_END)
    cs = [ChemoInfusion(Float64(c*CYCLE_LEN), p.TotalDose, p.DeltaC) for c in 0:N_CYCLES-1]
    gs = if gcsf_flag == 0
        GCSFInjection{Float64,Float64}[]
    else
        [GCSFInjection(Float64(c*CYCLE_LEN) + x_inj[c+1], DOSE_AMT) for c in 0:N_CYCLES-1]
    end
    sol = solve_scenario_undeclared(p, tspan;
        chemo_schedule=cs, gcsf_schedule=gs,
        smooth_chemo=true,  chemo_smooth_shape=:sigmoid, chemo_smooth_width=SIGMOID_EPS,
        smooth_gcsf=(gcsf_flag==1), gcsf_smooth_shape=:sigmoid, gcsf_smooth_width=SIGMOID_EPS,
        reltol=1e-8, abstol=1e-8, dtmax=1e-2, saveat=SAVEAT)
    return sol.t, [ANC_SCALE * sol.u[i][ANC_IDX] for i in eachindex(sol.t)]
end

function solve_anc_7c_daily()
    p = default_parameters(Float64)
    p.AdminChemo=1; p.AdminGCSF=1; p.DayAdminChemo=0.0; p.DeltaC=CHEMO_W
    p.Period=CYCLE_LEN; p.NumAdminsChemo=N_CYCLES; p.DoseChemo=4000.0
    p.TotalDose=4000.0*p.BSA; p.Dose=DOSE_AMT
    recompute_derived!(p)
    tspan = (0.0, T_END)
    cs = [ChemoInfusion(Float64(c*CYCLE_LEN), p.TotalDose, p.DeltaC) for c in 0:N_CYCLES-1]
    # Daily G-CSF: days 1–13 of each cycle
    gs = GCSFInjection{Float64,Float64}[]
    for c in 0:N_CYCLES-1
        for k in 0:12
            push!(gs, GCSFInjection(Float64(c*CYCLE_LEN) + 1.0 + k, DOSE_AMT))
        end
    end
    sol = solve_scenario_undeclared(p, tspan;
        chemo_schedule=cs, gcsf_schedule=gs,
        smooth_chemo=true,  chemo_smooth_shape=:sigmoid, chemo_smooth_width=SIGMOID_EPS,
        smooth_gcsf=true,   gcsf_smooth_shape=:sigmoid,  gcsf_smooth_width=SIGMOID_EPS,
        reltol=1e-8, abstol=1e-8, dtmax=1e-2, saveat=SAVEAT)
    return sol.t, [ANC_SCALE * sol.u[i][ANC_IDX] for i in eachindex(sol.t)]
end

# ── Deficit helper ─────────────────────────────────────────
function compute_deficit_7c(t, anc)
    loss = 0.0
    for i in 2:length(t)
        dt = t[i]-t[i-1]
        a1 = anc[i-1]; a2 = anc[i]
        loss += 0.5*(max(0.0, ANC_THR-a1) + max(0.0, ANC_THR-a2))*dt
    end
    return loss
end

# ── Main benchmark ─────────────────────────────────────────
function main(args=ARGS)
    Random.seed!(42)

    options = parse_cli(args)
    preset = options["preset"]
    methods = options["methods"]
    results_dir = abspath(options["output"])
    mkpath(results_dir)
    budget = preset == "quick" ? 20 : 600

    println("="^70)
    println("  6-Method Benchmark  —  G-CSF Timing  ($(N_CYCLES) cycles CHOP-14)")
    println("  Dimension: $(DIM)  (one injection time per cycle)")
    println("  Loss = ∫₀⁹⁸ max(0, 2.0 − ANC) dt   [ANC·days below grade 3/4]")
    println("  Initial: day $(T_INIT) every cycle, 300 μg G-CSF")
    println("  Preset: $(preset); methods: $(methods)")
    println("  Budget: $(budget) forward DDE solves per method")
    println("  AD+ADAM  → $(budget÷2) iters @ 2 solves/iter")
    println("  FD+ADAM  → $(budget÷(2*DIM+1)) iters @ $(2*DIM+1) solves/iter")
    println("="^70)

    # ── Warm-up (JIT) ─────────────────────────────────────
    print("  Warming up JIT (7-cycle DDE)... ")
    x0 = fill(T_INIT, DIM)
    timing_loss_7c(x0)
    ad_gradient_7c(x0)
    println("done\n")

    # ── Run all 6 methods ─────────────────────────────────
    runners = [
        ("AD + ADAM", () -> run_ad_adam_7c(budget=budget, lr=0.05)),
        ("AD + L-BFGS", () -> run_ad_lbfgs_7c(budget=budget)),
    ]
    if methods == "all"
        append!(runners, [
            ("FD + ADAM", () -> run_fd_adam_7c(budget=budget, lr=0.05)),
            ("FD + L-BFGS", () -> run_fd_lbfgs_7c(budget=budget)),
            ("Nelder-Mead", () -> run_nelder_mead_7c(budget=budget)),
            ("Simulated Annealing", () -> run_sim_anneal_7c(budget=budget)),
        ])
    end
    results = MethodResult7C[]
    for (i, (label, runner)) in enumerate(runners)
        @printf("  [%d/%d] %s...\n", i, length(runners), label)
        r = runner()
        push!(results, r)
        days_str = join([@sprintf("%.1f", d) for d in r.best_x], ", ")
        @printf("         loss=%.4f  days=[%s]  (%d solves, %.1fs)\n",
                r.best_loss, days_str, r.total_solves, r.wall_time)
    end

    # ── Summary table ─────────────────────────────────────
    println("\n", "="^70)
    println("  Summary")
    println("="^70)
    @printf("  %-16s  %10s  %8s  %10s  %s\n",
            "Method", "Best Loss", "Solves", "Time (s)", "Best Days")
    println("  ", "-"^72)
    for r in results
        days_str = join([@sprintf("%.1f", d) for d in r.best_x], ", ")
        @printf("  %-16s  %10.4f  %8d  %10.2f  [%s]\n",
                r.name, r.best_loss, r.total_solves, r.wall_time, days_str)
    end

    # ── Reference scenarios ───────────────────────────────
    x_none   = fill(0.0, DIM)
    x_day4   = fill(T_INIT, DIM)
    x_day8   = fill(8.0, DIM)

    t_no, anc_no       = solve_anc_7c(x_none; gcsf_flag=0)
    loss_none          = compute_deficit_7c(t_no, anc_no)
    loss_day4          = timing_loss_7c_f64(x_day4)
    loss_day8          = timing_loss_7c_f64(x_day8)
    t_daily, anc_daily = solve_anc_7c_daily()
    loss_daily         = compute_deficit_7c(t_daily, anc_daily)

    # Best AD result
    ad_results = filter(r -> startswith(r.name, "AD"), results)
    best_ad = sort(ad_results, by=r -> r.best_loss)[1]
    x_opt = best_ad.best_x; loss_opt = best_ad.best_loss

    @printf("\n  References (7-cycle):\n")
    @printf("    no-GCSF     = %.4f\n", loss_none)
    @printf("    day-4 (init)= %.4f\n", loss_day4)
    @printf("    day-8 every = %.4f\n", loss_day8)
    @printf("    daily       = %.4f\n", loss_daily)
    opt_days_str = join([@sprintf("%.1f", d) for d in x_opt], ", ")
    @printf("    AD-opt      = %.4f  days=[%s]\n", loss_opt, opt_days_str)

    # ═════════════════════════════════════════════════════════
    #  SAVE CONVERGENCE HISTORY CSV
    # ═════════════════════════════════════════════════════════
    println("\n  Saving CSVs...")

    rows = NamedTuple[]
    for r in results
        for j in eachindex(r.loss_history)
            push!(rows, (method=r.name, step=j,
                         solves=r.solve_history[j],
                         wall_s=round(r.time_history[j]; digits=4),
                         best_loss=round(r.loss_history[j]; digits=6)))
        end
    end
    conv_path = joinpath(results_dir, "NeutropeniaDDE_convergence.csv")
    CSV.write(conv_path, DataFrame(rows))
    println("    ", conv_path)

    # Summary table
    summary_rows = [(method=r.name, best_loss=r.best_loss,
                     best_days=join([@sprintf("%.2f", d) for d in r.best_x], ";"),
                     total_solves=r.total_solves, wall_s=r.wall_time)
                    for r in results]
    summ_path = joinpath(results_dir, "NeutropeniaDDE_summary.csv")
    CSV.write(summ_path, DataFrame(summary_rows))
    println("    ", summ_path)

    # ANC trajectories for plotting
    scenarios = [
        ("no_gcsf",    x_none,  t_no,    anc_no,    loss_none),
        ("day8_every", x_day8,  solve_anc_7c(x_day8)..., loss_day8),
        ("daily",      x_none,  t_daily, anc_daily,  loss_daily),
        ("ad_opt",     x_opt,   solve_anc_7c(x_opt)...,  loss_opt),
    ]
    anc_rows = NamedTuple[]
    for (label, x_vec, ts, ancs, _loss) in scenarios
        days_str = join([@sprintf("%.2f", d) for d in x_vec], ";")
        for j in eachindex(ts)
            push!(anc_rows, (scenario=label, inj_days=days_str, loss=_loss,
                             time=ts[j], anc=ancs[j]))
        end
    end
    anc_path = joinpath(results_dir, "NeutropeniaDDE_anc_traces.csv")
    CSV.write(anc_path, DataFrame(anc_rows))
    println("    ", anc_path)

    # ═════════════════════════════════════════════════════════
    #  SAVE CONFIGURATION JSON
    # ═════════════════════════════════════════════════════════
    println("  Saving configuration JSON...")

    config = Dict(
        "experiment" => Dict(
            "description" => "6-method benchmark: G-CSF timing optimisation, $(N_CYCLES) cycles CHOP-14",
            "date"        => string(Dates.today()),
            "n_cycles"    => N_CYCLES,
            "dimension"   => DIM,
            "preset" => preset,
            "methods" => methods,
            "budget_solves" => budget,
            "initial_time"  => T_INIT,
            "bounds"        => [T_MIN, T_MAX],
            "tspan_days"    => [0.0, T_END],
        ),
        "dde_solver" => Dict(
            "method"     => "MethodOfSteps(RK4())",
            "delays"     => "undeclared (no dependent_lags)",
            "reltol"     => 1e-8,
            "abstol"     => 1e-8,
            "dtmax"      => 1e-2,
            "saveat"     => SAVEAT,
            "tspan"      => [0.0, T_END],
        ),
        "dosing" => Dict(
            "chemo_smooth"        => true,
            "chemo_smooth_shape"  => "sigmoid",
            "chemo_smooth_width"  => SIGMOID_EPS,
            "gcsf_smooth"         => true,
            "gcsf_smooth_shape"   => "sigmoid",
            "gcsf_smooth_width"   => SIGMOID_EPS,
            "gcsf_dose_ng"        => DOSE_AMT,
            "gcsf_dose_ug"        => DOSE_AMT / 1000,
            "chemo_dose_mg_m2"    => 4000.0,
            "chemo_duration_days" => CHEMO_W,
            "chemo_events"        => N_CYCLES,
            "gcsf_events_per_cycle" => 1,
        ),
        "ad_route" => Dict(
            "library"          => "ForwardDiff.jl",
            "mode"             => "forward-mode (Dual numbers, chunk_size=$(DIM))",
            "sensealg"         => "nothing (duals propagated through solver)",
            "safe_sigmoid"     => true,
            "safe_power_eps"   => 1e-30,
        ),
        "loss" => Dict(
            "type"       => "deficit_area",
            "formula"    => "∫₀⁹⁸ max(0, threshold - ANC(t)) dt",
            "threshold"  => ANC_THR,
            "quadrature" => "trapezoidal on saveat grid",
            "anc_scale"  => ANC_SCALE,
            "anc_index"  => ANC_IDX,
        ),
        "scaling_advantage" => Dict(
            "AD_solves_per_grad" => 1,
            "FD_solves_per_grad" => 2 * DIM,
            "ratio"              => 2 * DIM,
            "AD_ADAM_iters"      => budget ÷ 2,
            "FD_ADAM_iters"      => budget ÷ (2 * DIM + 1),
        ),
        "optimisers" => Dict(
            "AD+ADAM"     => Dict("lr"=>0.05, "β1"=>0.9, "β2"=>0.999, "solves_per_iter"=>2),
            "AD+LBFGS"   => Dict("algorithm"=>"Fminbox(LBFGS())", "grad"=>"ForwardDiff",
                                 "budget_enforcement"=>"BudgetExhausted exception"),
            "FD+ADAM"     => Dict("lr"=>0.05, "β1"=>0.9, "β2"=>0.999, "fd_step"=>FD_STEP,
                                 "solves_per_iter"=>2*DIM+1),
            "FD+LBFGS"   => Dict("algorithm"=>"Fminbox(LBFGS())", "grad"=>"central FD (Optim default)",
                                 "budget_enforcement"=>"BudgetExhausted exception"),
            "Nelder-Mead"  => Dict("algorithm"=>"NelderMead()",
                                  "budget_enforcement"=>"BudgetExhausted exception"),
            "Simulated Annealing" => Dict("algorithm"=>"SAMIN(rt=0.9)",
                                  "budget_enforcement"=>"BudgetExhausted exception"),
        ),
        "results_summary" => Dict(
            r.name => Dict("best_loss"=>r.best_loss,
                           "best_days"=>r.best_x,
                           "total_solves"=>r.total_solves, "wall_s"=>r.wall_time)
            for r in results
        ),
        "references" => Dict(
            "no_gcsf"    => loss_none,
            "day_4"      => loss_day4,
            "day_8"      => loss_day8,
            "daily"      => loss_daily,
            "ad_opt"     => loss_opt,
            "ad_opt_days"=> x_opt,
        ),
    )

    json_path = joinpath(results_dir, "NeutropeniaDDE_config.json")
    open(json_path, "w") do io
        JSON3.pretty(io, config)
    end
    println("    ", json_path)

    println("\n  Done ✓  —  run Figures/plot_Figure3.jl to generate figures.")
    return results
end

if abspath(PROGRAM_FILE) == @__FILE__
    main(ARGS)
end
